### ISSUE TITLE
Is it possible to render chart with scrollbar for large amount of data?

### ISSUE THREAD

**Issue by teodosii** [amcharts/amcharts4#3353]
Hello,

On a large data SankeyDiagram chart, is it possible to have the chart rendered with scrolling option? Like for a basic example it wouldn't need a scrollbar, let's say it will need `300px` in height at most and will suffice.

But for anything else I'd like to hit up to `600px` let's say and everything else is scrollable.

Is it possible to achieve this?

I tried a CSS approach like

```css
#chartdiv {
  width: 100%;
  height: 400px;
  overflow-y: auto;
}

.chart-wrapper {
  height: auto;
  max-height: 300px;
  overflow-y: auto;
}
```

but this doesn't work for small amount of data. I guess I could also threshold the max vertical size and based on that to render into the wrapper or not, but feels a bit hacky. Does amcharts have a smart solution for this?

[Pen](https://codepen.io/raresm2020/pen/PobdYOX) this pen shows the css approach, but it fails for small data.

Thank you for all the support!
